[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/googlefbfe6e66b2f612ec.html"
  to = "/googlefbfe6e66b2f612ec.html"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
